app = "microcosm-api"
primary_region = "lhr"

[build]

[env]
  VOXL_API_PORT = "4001"
  VOXL_API_DATA_DIR = "/data"

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1

[[mounts]]
  source = "microcosm_data"
  destination = "/data"
